### PR TITLE
Add project-submission GH issue template

### PR DESCRIPTION
**Pull request by valencik**
Here's a first attempt at an issue template for new project submissions.
Some prior discussion in https://github.com/typelevel/governance/issues/57.

When users go to create a new issue they'll see the option to select a template or open a blank issue:
Screenshot from 2022-11-04 07-45-43

And then if they select the template it'll look something like this:
Screenshot from 2022-11-04 07-46-07

### CODE REVIEW

**Review by jducoeur — APPROVED** [review]

**Comment by samspills** [comment]
What do you think about including the `if project is accepted` checklist in this issue as well?

**Comment by valencik** [comment]
> What do you think about including the `if project is accepted` checklist in this issue as well?

I think we could definitely link to a checklist here.
But I wouldn't want to inline it. Mostly because I want to keep things simple and the instructions change slightly based on whether or not the project will be affiliate or organization.

So let's perhaps create a doc in the repo with the migration checklist and then we can add a note about it in this template?

**Comment by valencik** [comment]
Alternatively we could have another issue template for the migration work. Then project submission and all the things that happen next are separate, leaving the project submission issues focused.

Other project submissions pretty much wrap up and close before or just after the repo migration:
- https://github.com/typelevel/governance/issues/39#issuecomment-1100163757
- https://github.com/typelevel/governance/issues/41#issuecomment-1109960715
- https://github.com/typelevel/governance/issues/43#issuecomment-1147038267

So repo migration and GH team setup it seems.
Things like adding it to the site and optionally announcing it on the blog or social media is kind of a long tail followup that it probably best tracked in a separate issue.

**Comment by valencik** [comment]
I've added a new template that tracks the migration work and optional announcement items.
I've also named the files with leading numbers to ensure the migration checklist appears below the project submission template.

Should look like:
Screen Shot 2022-11-05 at 9 37 52 AM

**Review by samspills — APPROVED** [review]

**Review by jducoeur — APPROVED** [review]

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
